### ISSUE TITLE
Later yellowstone versions break compatibility with solana 1.16 apps

### ISSUE THREAD

**Issue by soapyp** [blockworks-foundation/mango-feeds#20]
Upgrading yellowstone libs caused a conflict with the version of tokio required by tonic (1.32.0) and by solana 1.16 (1.14.1)
I solved this in mango-v4 (https://github.com/blockworks-foundation/mango-v4/pull/851) by patching solana, but the upgrade and unpinning in https://github.com/solana-labs/solana/commit/c02021173db45aa9bc5ce64af0ee50097318913a should resolve this once we upgrade to 1.17.

**Comment by grooviegermanikus** [comment]
thx!
