### ISSUE TITLE
Support for Solana Version 1.16

### ISSUE THREAD

**Issue by mschneider** [blockworks-foundation/mango-feeds#7]
* 1.16.1+
* 1.14.20+

See related [mango-v4 issue](https://github.com/blockworks-foundation/mango-v4/issues/713)

**Comment by grooviegermanikus** [comment]
connector - mango-feeds - mango_v4_client - mango_v4 have a circular dependency which we need to break - ongoing

**Comment by grooviegermanikus** [comment]
updated [mango-v4](https://github.com/blockworks-foundation/mango-v4/pull/718) and [mango-feeds](https://github.com/blockworks-foundation/mango-feeds/pull/16)
